"""modified customer relationships

Revision ID: 0f7c7b5cfd4b
Revises: 3ad6c6dbf62f
Create Date: 2024-06-12 21:17:31.725062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7c7b5cfd4b'
down_revision: Union[str, None] = '3ad6c6dbf62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
