"""add last_login nullable

Revision ID: 2d6a3d695d93
Revises: c827838725f6
Create Date: 2024-06-05 18:32:06.738127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d6a3d695d93'
down_revision: Union[str, None] = 'c827838725f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
