"""Subscription table added

Revision ID: 6748ce996cdd
Revises: 8abdbd8d2f35
Create Date: 2024-06-11 10:00:22.451056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6748ce996cdd'
down_revision: Union[str, None] = '8abdbd8d2f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('bronze', 'silver', 'gold', name='myenum'), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('name', table_name='cinemas')
    op.drop_index('name', table_name='movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'movies', ['name'], unique=True)
    op.create_index('name', 'cinemas', ['name'], unique=True)
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
