"""upgraded some tables

Revision ID: a296cd047cd2
Revises: 0f7c7b5cfd4b
Create Date: 2024-06-14 09:10:44.364510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a296cd047cd2'
down_revision: Union[str, None] = '0f7c7b5cfd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
