"""modified customer

Revision ID: a7ceadff910f
Revises: 6748ce996cdd
Create Date: 2024-06-11 17:14:56.979519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ceadff910f'
down_revision: Union[str, None] = '6748ce996cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('wallet', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'wallet')
    # ### end Alembic commands ###
