"""ticket table added

Revision ID: a7dafb262edf
Revises: 32a3afd0be56
Create Date: 2024-06-14 14:24:45.899372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dafb262edf'
down_revision: Union[str, None] = '32a3afd0be56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sans_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sans_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sans_id'], ['sans.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('sans_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('purchased_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['sans_id'], ['sans.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['sans_seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sans')
    op.drop_table('tickets')
    op.drop_table('sans_seats')
    # ### end Alembic commands ###
